FROM techtucson/apache_php8.3_oci8_v21.13

RUN mv /var/www/html/public/index.php /var/www/html/public/info.php

ADD apache/index.html /var/www/html/public/index.html
ADD apache/clouds.jpg /var/www/html/public/clouds.jpg
